version: 2

dependencies:
    override:
        - sudo pip install awscli

jobs:
  steps:
    - checkout
    - deploy:
        branch: master
        commands:
          - aws s3 sync /home/ubuntu/persona-page s3://s3awscd --delete
